import '../globals.css';
import {NextIntlClientProvider, useLocale} from 'next-intl';
import {notFound} from 'next/navigation';
import React from "react";

export const metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default async function RootLayout({
   children
}: {
   children: React.ReactNode
}) {
   const locale = useLocale();

   let messages;
   try {
      messages = (await import(`../../messages/${locale}.json`)).default;
   } catch (error) {
      notFound();
   }

   return (
      <html lang={locale}>
      <body>
      <main className="min-h-screen bg-background flex flex-col items-center">
         <NextIntlClientProvider locale={locale} messages={messages}>
            {children}
         </NextIntlClientProvider>
      </main>
      </body>
      </html>
   )
}
