import './globals.css';
import {getPeople} from "@/utils/people";
import Link from "next/link";

export const metadata = {
   title: 'Stories Dashboard',
   description: 'Generated by Next.js',
}

export default function RootLayout({
   children,
}: {
   children: React.ReactNode
}) {
   return (
      <html lang="en">
      <body>
      <nav className="flex gap-8 py-4 px-20">
         {getPeople().map((personName) => {
            return (
               <Link className="underline hover:text-blue-500" href={`/stories-dashboard/${personName.toLowerCase()}`}>
                  <button>{personName.toUpperCase()}</button>
               </Link>
            )
         })}
      </nav>
      {children}
      </body>
      </html>
   )
}
